//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facts.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FactService")]
    public interface FactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FactService/GetData", ReplyAction="http://tempuri.org/FactService/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FactService/GetData", ReplyAction="http://tempuri.org/FactService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FactService/GetExcel", ReplyAction="http://tempuri.org/FactService/GetExcelResponse")]
        System.IO.Stream GetExcel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FactService/GetExcel", ReplyAction="http://tempuri.org/FactService/GetExcelResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetExcelAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FactServiceChannel : Facts.ServiceReference1.FactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactServiceClient : System.ServiceModel.ClientBase<Facts.ServiceReference1.FactService>, Facts.ServiceReference1.FactService {
        
        public FactServiceClient() {
        }
        
        public FactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.IO.Stream GetExcel() {
            return base.Channel.GetExcel();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetExcelAsync() {
            return base.Channel.GetExcelAsync();
        }
    }
}
